[{"name": "test.test_file_listing.FileListing.test_called", "status": "errored", "message": "(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \\UXXXXXXXX escape (file_listing.py, line 32)", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\test\\test_file_listing.py\", line 60, in test_called\n    patch(ph('re.compile'), side_effect=re.compile) as c,\\\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\tmc\\utils.py\", line 207, in __call__\n    getattr(importlib.import_module(self.m), parts[-1])   # attribute\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\importlib\\__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 846, in exec_module\n", "  File \"<frozen importlib._bootstrap_external>\", line 983, in get_code\n", "  File \"<frozen importlib._bootstrap_external>\", line 913, in source_to_code\n", "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n"]}, {"name": "test.test_file_listing.FileListing.test_content", "status": "failed", "message": "Function file_listing was not found in file src.file_listing.", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\test\\test_file_listing.py\", line 28, in test_content\n    result=file_listing()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\tmc\\utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_file_listing.FileListing.test_names", "status": "failed", "message": "Function file_listing was not found in file src.file_listing.", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\test\\test_file_listing.py\", line 50, in test_names\n    result = file_listing()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\tmc\\utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_file_listing.FileListing.test_size", "status": "failed", "message": "Function file_listing was not found in file src.file_listing.", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\test\\test_file_listing.py\", line 19, in test_size\n    result=file_listing()\n", "  File \"C:\\Users\\Tec\\Python-og-DataAnalyse-1\\excercises\\part02\\e02_file_listing\\tmc\\utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}]