[{"name": "test.test_hello_world.HelloWorld.test_first", "status": "failed", "message": "Function main was not found in file src.hello_world.", "passed": false, "points": ["p01-01.1"], "backtrace": ["  File \"/Users/soren/opt/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/soren/opt/anaconda3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/Users/soren/TEC/HF/UnvForløb.s0ren.github/PythonData/mooc/exercises/part01/e01_hello_world/test/test_hello_world.py\", line 18, in test_first\n    main()\n", "  File \"/Users/soren/TEC/HF/UnvForløb.s0ren.github/PythonData/mooc/exercises/part01/e01_hello_world/tmc/utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}]