[{"name": "test.test_sum_equation.SumEquation.test_empty", "status": "failed", "message": "[]", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\test\\test_sum_equation.py\", line 38, in test_empty\n    result = sum_equation([])\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\tmc\\utils.py\", line 79, in fail\n    raise AssertionError(args[0])\n"]}, {"name": "test.test_sum_equation.SumEquation.test_first", "status": "failed", "message": "[1, 5, 7]", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\test\\test_sum_equation.py\", line 21, in test_first\n    result = sum_equation(L)\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\tmc\\utils.py\", line 79, in fail\n    raise AssertionError(args[0])\n"]}, {"name": "test.test_sum_equation.SumEquation.test_random", "status": "failed", "message": "[70, 13, 95, 43, 85, 2, 22, 62, 65, 81, 6, 54, 59, 44, 20, 46, 12, 74, 95, 2, 82, 83, 86, 37, 40, 69, 7, 87, 24, 16, 14, 48, 42, 50, 45, 24, 40, 41, 21, 47, 99, 78, 62, 77, 23, 74, 92, 39, 22, 86]", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\test\\test_sum_equation.py\", line 27, in test_random\n    result = sum_equation(L)\n", "  File \"C:\\Users\\nsflo\\python\\excercises\\part01\\e19_sum_equation\\tmc\\utils.py\", line 79, in fail\n    raise AssertionError(args[0])\n"]}]