[{"name": "test.test_hello_world.HelloWorld.test_first", "status": "failed", "message": "Function main was not found in file src.hello_world.", "passed": false, "points": ["p01-01.1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\smag\\OneDrive - TEC\\Data HF\\undervisningsforløb-github\\Python-og-DataAnalyse\\excercises\\part01\\e01_hello_world\\test\\test_hello_world.py\", line 18, in test_first\n    main()\n", "  File \"C:\\Users\\smag\\OneDrive - TEC\\Data HF\\undervisningsforløb-github\\Python-og-DataAnalyse\\excercises\\part01\\e01_hello_world\\tmc\\utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}]